#!/bin/bash

source ./parameters

if [ $# != 1 ]
then
        echo "usage $0 interface"
        exit 1
fi

ip=$(/sbin/ifconfig $1 | grep 'inet addr': | cut -d: -f2 | cut -d" " -f1)

echo $ip

awk -v features=$FEATURES 'BEGIN { exit index(features, "odl-netconf-all") }'
if [ "$?" != "0" ];
then
	echo "mounting netconf nodes"
	while read -r line
	do
		addr=$(echo $line | cut -f1 -d" ")
		name=$(echo $line | cut -f2 -d" ")
		python/put-node.py localhost $addr $name
		sleep 2

		while true;
		do
      	  		python/is-node-connected.py $ip $name 
	        	if [ $? -eq 0 ]
        		then
                		echo "NETCONF node $name up"
                		break
        		else
                		sleep 2
        		fi
		done
	done < nodes
fi

awk -v features=$FEATURES 'BEGIN { exit index(features, "odl-bgpcep-bgp") }'
if [ "$?" != "0" ];
then
	echo "configuring BGP"
	# configure BGP RIB
	python/put-bgp-rib.py $ip
	
	# configure app peer	
	python/put-app-rib.py $ip 1.2.3.4 

	if $dcloud;
	then	
		echo "configuring BGP peer"
		req='{"request": [{"option": "addBGP", "bgp_ip":"'$ip'"}]}'
		echo $req
		echo $req | curl -s -X POST http://198.18.133.1:8010/virl_client -H "Content-Type: application/json" -d @-
	fi

	# configure ODL to talk to BGP peer
	python/put-bgp-peer.py $ip $BGP_PEER
fi

awk -v features=$FEATURES 'BEGIN { exit index(features, "odl-bgpcep-pcep") }'
if [ "$?" != "0" ];
then
	if $dcloud;
	then
		echo "configuring PCE-P"
		req='{"request": [{"option": "addPCEP", "pcep_ip":"'$ip'"}]}'
		echo $req
		echo $req | curl -s -X POST http://198.18.133.1:8010/virl_client -H "Content-Type: application/json" -d @-
	fi
fi 
