#!/bin/bash

source ./parameters
unamestr=$(uname)
mkdir -p $DISTRO/etc/opendaylight/karaf

if grep -q "1MB" $DISTRO/etc/org.ops4j.pax.logging.cfg;
then
	echo "configuring logging and features"

	if [[ $unamestr == 'Darwin' ]]; then 
		sed -i '' 's/1MB/10000MB/' $DISTRO/etc/org.ops4j.pax.logging.cfg
	elif [[ $unamestr == 'Linux' ]]; then
		sed -i 's/1MB/10000MB/' $DISTRO/etc/org.ops4j.pax.logging.cfg
	fi

	cat logs >> $DISTRO/etc/org.ops4j.pax.logging.cfg 	

	# add features
	if [[ $unamestr == 'Darwin' ]]; then
		sed -i '' '/^featuresBoot=/ s/$/,'$FEATURES'/' $DISTRO/etc/org.apache.karaf.features.cfg
	elif [[ $unamestr == 'Linux' ]]; then
		sed -i '/^featuresBoot=/ s/$/,'$FEATURES'/' $DISTRO/etc/org.apache.karaf.features.cfg
	fi
fi
