#!/bin/bash

source ./parameters

rm -rf $DISTRO/data
rm -rf $DISTRO/etc/opendaylight/current
rm -rf $DISTRO/cache
rm -rf $DISTRO/journal
rm -rf $DISTRO/snapshots
rm -rf $DISTRO/instances

source $DISTRO/bin/setenv
$DISTRO/bin/start

unamestr=$(uname)

while true;
do
	if [[ $unamestr == 'Darwin' ]]; then
		up=$(netstat -an | grep *.8181 | wc -l)
	elif [[ $unamestr == 'Linux' ]]; then
		up=$(netstat -an | grep *:8181 | wc -l)
	fi

	if [ $up != 0 ]
	then
		if [ $VERSION == 'Oxygen' ]; then
			echo "ODL is ready"
			exit 0
		else
			echo "ODL is nearly ready"
			break
		fi
	else
		echo "ODL is starting"
		sleep 5
	fi 
done

while true;
do
	ready=$(curl http://admin:admin@localhost:8181/restconf/operational/network-topology:network-topology/topology/topology-netconf/node/controller-config 2>&1)
	if echo $ready | grep -q "connected";
	then
		echo "ODL is ready!"
		exit 0
	else
		echo "ODL is almost ready"
		sleep 5
	fi
done
